### ISSUE TITLE
Question about U-Net

### ISSUE THREAD

**Issue by tommy-qichang** [ultrai/Chap_2#1]
Hi, 
Great work for migration U-net from caffe to torch.
I've one question concerning about overlap-tile strategy.
Is the tile size in your code is 64x64? So after the training process, do we need to combine all tiles together to recover a output image? How to do that part?

Thanks in advance.

**Comment by ultrai** [comment]
Thanks for your interest ad sorry for delayed reply.
To exactly replicate U-net one need to process a 64x 64 tile and mosaic all those tiles at the output.
But considereing a  256X256 or 496X496  image as input did no much harm to the predictions
